--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/python:3.7"
    steps: 
      - checkout
      - 
        run: 
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
          name: "install dependencies"
      - 
        run: 
          command: |-
              . venv/bin/activate
              flake8 --exclude=venv* --statistics
              pytest -v --cov=calculator
          name: "run tests"
    working_directory: ~/repo
version: 2
