--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/python:3.7"
    steps: 
      - checkout
      - 
        run: 
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
          name: "install dependencies"
      - 
        run: 
          command: ". venv/bin/activate\n\
              flake8 --exclude=venv* --statistics\n\
              pytest -v --cov=calculator                "
          name: "run tests"
    working_directory: ~/CalculatorApp
version: 2
